# Generated by Django 5.0.3 on 2024-06-28 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('phno', models.CharField(null=True)),
                ('pincode', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(999999)])),
            ],
            options={
                'db_table': 'address_table',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('chname', models.CharField(max_length=100)),
                ('cnumber', models.CharField()),
                ('expdate', models.CharField()),
                ('cvv', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=999), django.core.validators.MinValueValidator(limit_value=0)])),
            ],
            options={
                'db_table': 'card_table',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='sdp12', max_length=100)),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
        migrations.CreateModel(
            name='Upi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('upi', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'upi_table',
            },
        ),
    ]
