# Generated by Django 5.0.3 on 2024-06-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=225, unique=True)),
                ('password', models.CharField(default='sdp12', max_length=100)),
            ],
            options={
                'db_table': 'dealer_table',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('offer', models.IntegerField()),
                ('price', models.IntegerField(null=True)),
                ('cart', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'item_table',
            },
        ),
    ]
